version: '3'
services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    env_file: 
      - ./api/src/.env
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    env_file:
      - ./api/src/.env
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Том для хранения данных

  hash-generator:
    build: ./hash_generator  
    ports:
      - "8001:8001"
    env_file: 
      - ./hash_generator/.env
    # environment:
    #   REDIS_HOST: ${HOST_REDIS}
    #   REDIS_PORT: ${PORT_REDIS}
    #   MAX_COUNT:  ${MAX_COUNT}
    #   HASH_CACHE_KEY: ${HASH_CACHE_KEY}
    #   REDIS_DB: ${DB_REDIS}
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  frontend:
    build: ./front
    ports:
      - "3000:80"

# volumes для сохранения данных
volumes:
  postgres_data:


